### PR TITLE
Phrases in Variants

### PR DESCRIPTION
**Pull request by groverlynn**
Add phrases in other commonly used ideograph variants Correct a few wrong ideographs

### CODE REVIEW

**Comment by LEOYoon-Tsaw** [comment]
説、吃 are not recommended variants, so are excluded in Traditional Chinese entries

**Comment by groverlynn** [comment]
> 説、吃 are not recommended variants, so are excluded in Traditional Chinese entries

"説" is the standard variant in HK/Macau Traditional Chinese.
"吃" is the dominant variant, and "喫" is rarely used in modern Chinese, though very common in Japanese.

When opencc is set to adopt HK standard, one cannot type "說" or "喫"; when set to TW standard, one cannot type "喫" either. It's necessary to include these variants, especially in scenarios where emoji is the last simplifier.

**Comment by LEOYoon-Tsaw** [comment]
**Those variants are way too many.** This project will aim to limit its coverage to preferred words in Rime's essay. Simplified Chinese is included simply because its vast adoption, I'm not even sure if I should keep them in, I would not expand to try to include all variants in the world.

For people who use regional preferred variants, they are encouraged to use OpenCC for conversion from Rime's standard. In that case, Emoji conversion will work perfectly since behind the scene, both conversions are based on Rime's standard.

But since OpenCC typically doesn't convert difference in preferred words, I would love to try to include all words for any Emoji based on different regional practices. (Eg. 草莓、士多啤梨 for 🍓 are both included)

If you have a customized dictionary for your input scheme, and want a Emoji conversion table fully adapted to your regional variant choices, make a copy.

**Comment by groverlynn** [comment]
> 



> **Those variants are way too many.** This project will aim to limit its coverage to preferred words in Rime's essay. Simplified Chinese is included simply because its vast adoption, I'm not even sure if I should keep them in, I would not expand to try to include all variants in the world.
> 
> For people who use regional preferred variants, they are encouraged to use OpenCC for conversion from Rime's standard. In that case, Emoji conversion will work perfectly since behind the scene, both conversions are based on Rime's standard.
> 
> But since OpenCC typically doesn't convert difference in preferred words, I would love to try to include all words for any Emoji based on different regional practices. (Eg. 草莓、士多啤梨 for 🍓 are both included)
> 
> If you have a customized dictionary for your input scheme, and want a Emoji conversion table fully adapted to your regional variant choices, make a copy.
 
Not really. Your order of simplification is emoji first, then regional variations. This creates two big problems. Firstly, the tips of the emoji are likely not in the selected transcript (rarely in simplified Chinese, and sometimes in TW or HK standard Traditional Chinese, but not in OpenCC standard either). This can be confusing sometimes, and is not what users expect to see when simplification/regionalization has been specifically turned on. 

Secondly, users of shape-based input schemes often bypasses opencc standard vocabulary in essay but go for the specific variant in mind. For instance, Taiwanese users will often type in the code for "著火", and rime will not convert it to "着火". If your emoji dictionary does not include phrase in TW variants, then the associated emoji "🔥" will not show up. On the other hand, Hong Kong users probably aren't able to find "🍜" under "麪", if your dictionary only links "🍜" with the TW variant "麵".

The situation gets even more complicated when the phrase in the emoji dictionary is not in found essay and the phrase itself contains characters with one-to-two/multi or even multi-to-multi simplification projections. For instance, the emoji dictionary has a strange phrase "🧔🏻鬚男" which is not found in essay or any scheme's dictionaries. When a CN phonetic-based scheme user types and composes "须男" as a new phrase, opencc wrongfully back-converts it to "須男" and the use can never create "鬚男" in simplified mode, and never find this emoji under "xǖ nán".

**Comment by LEOYoon-Tsaw** [comment]
1. In the schema file, if Emoji conversion filter is listed prior to Hanzi conversion, Emoji will be converted from Rime's standard (then subsequently go through Hanzi conversion). So people who use TW or HK Hanzi filters will still have Emoji when they type using Rime. For example, if you have this and only this in Emoji OpenCC file:
```
藍藍	藍藍 🧢
```
When you use OpenCC to type simplified Chinese, `藍藍` in dictionary will first be converted to `藍藍` and `🧢`, then `藍藍` will be converted to `蓝蓝`. This will not work if the user use their own dictionary which disregards Rime's variant standard, but in that case, they should customize their own Emoji conversion as well.

2. Shape based input has the advantage of choosing the variant on user's will, they don't even need to speak Chinese, like a Japanese can also use shape based input to input Kanji. It's unrealistic to include all the variants. For example, for any word contains 「爲」, there needs to be 3 entries: 爲為为, for 麼, there are 麽麼么, the word 爲甚麼 needs 爲甚麼、為甚麼、爲甚麽、為甚麽、爲什麼、為什麼、爲什麽、為什麽、为什么, so many entries. Those users can use OpenCC to convert the Emoji table file on their own, the files are txt files, very easy to manipulate.

3. For cases like `🧔🏻	鬚男`, 鬚男 is not the only keyword, there are others as well (大鬍子、絡腮鬍 etc.）, if a prevalent keyword is not included, I will not refuse covering if I see. We can discuss this on case by case basis.

**Pull request merged**
